server:
  port: 9000
  servlet:
    session:
      timeout: 30m


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gmall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gmall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #设置主键自增

logging:
  level:
    com.wang.gmall: debug

gmall:
  thread:
    core-size: 5
    max-size: 20
    keep-alive-time: 200



