server:
  port: 21000

spring:
  application:
    name: gmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 6379

gmall:
  thread:
    core-size: 5
    max-size: 20
    keep-alive-time: 200
